import os
import sys
sys.path.insert(0, os.path.abspath('../source'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'
fontawesome_included = True

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "ablog",
    "myst_parser",
    "sphinx.ext.intersphinx",
    "sphinx_design",
    "sphinx_copybutton",
    "sphinxext.opengraph",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Jacob Arndt'
copyright = '2023, Jacob Arndt'
author = 'Jacob Arndt'

html_baseurl = "https://jwarndt.github.io/"
html_title = "Jacob Arndt"


blog_path = "posts"

# The "title" for the posts, used in active pages.  Default is ``'Blog'``.
blog_title = "Jacob Arndt"

# The path that you store your content in, this will be used for the browsing path
# on your published website
# e.g. blog_post_pattern = "blog/*/*"
blog_post_pattern = "posts/*/*"

post_date_format = "%b %d, %Y"
# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# version = '1.0.0'
# The full version, including alpha/beta/rc tags.
# release = '0.1.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "search_bar_text": "Search...",
    "show_prev_next": False,
    "navbar_center": [],
    "footer_items": ["copyright", "sphinx-version", "last-updated"],
}

html_sidebars = {
    "*": ["search-field.html", "sidebar-nav.html"],
    "posts": ["search-field.html", "sidebar-nav.html", "recentposts.html", "archives.html"],
    "posts/**": ["search-field.html", "sidebar-nav.html", "postcard.html"]
}